### PR TITLE
Releasing GCP Kubeflow distribution v1.6.1

### LINKED ISSUE #389: ASM make hydrate failed
asm make file will use `asmcli-precheck` during the hydrate, where the `bash` built in commands `pushd`, `popd` are used.
This will make the runtime error because of the program  default`/bin/sh' is used as the shell.

```bash
asmcli: -------------
asmcli: Successfully validated all requirements to install ASM.
pushd upstream && ./istioctl experimental precheck && popd
/bin/sh: 1: pushd: Permission denied
make[1]: *** [Makefile:75: asmcli-precheck] Error 127
```

### LINKED ISSUE #391: Upgrade MySQL to 8.0
As MySQL 8 is a default version in GCP and katib, it was proposed to upgrade MySQL version to 8.0.

        cc @gkcalat for upgrading MySQL version in the future release.

_Originally posted by @zijianjoy in https://github.com/kubeflow/gcp-blueprints/issues/382#issuecomment-1255648227_
     
Additional docs:
* [MySQL 8.0 release notes](https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html)
* [Instruction on upgrading SQL](https://cloud.google.com/sql/docs/mysql/upgrade-major-db-version-inplace#plan_a_major_version_upgrade)
* [GCP MySQL versions](https://cloud.google.com/sql/docs/mysql/db-versions)
* [GCP supported machine types](https://cloud.google.com/sql/docs/mysql/create-instance#machine-types)
* [GCP DB settings](https://cloud.google.com/sql/docs/mysql/flags#rest-v1)

Consideration:
* [ ] Is it a breaking change for users using KF 1.6.0 and prior?
* [ ] Do we need to upgrade tier?
* [ ] Do we need to enforce `utf8` charset as MySQL8 migrated to `utf8mb4`?

### LINKED ISSUE #392: No metrics shown in the UI
Get the following error from api-server
```
E1014 05:37:15.254214       7 error.go:297] InternalError: Unauthenticated: Request header error: there is no user identity header.: Request header error: there is no user identity header.
Failed to authorize with API resource references
github.com/kubeflow/pipelines/backend/src/common/util.Wrap
        /go/src/github.com/kubeflow/pipelines/backend/src/common/util/error.go:287
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).canAccessRun
        /go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:403
github.com/kubeflow/pipelines/backend/src/apiserver/server.(*RunServer).ReadArtifact
        /go/src/github.com/kubeflow/pipelines/backend/src/apiserver/server/run_server.go:315
github.com/kubeflow/pipelines/backend/api/go_client._RunService_ReadArtifact_Handler.func1
        /go/src/github.com/kubeflow/pipelines/backend/api/go_client/run.pb.go:2288
```

### PR DESCRIPTION
**Pull request by gkcalat**
Upgrading Kubeflow distribution for 1.6.1 release:
- [x] Upgrade upstream [manifests](https://github.com/kubeflow/manifests) to v 1.6.1
- [x] Upgrade upstream [KFP](https://github.com/kubeflow/pipelines) to v 2.0.0-alpha.6
- [x] Resolve #391 
- [x] Resolve #389 
- [x] Resolve #392
- [x] Updated CHANGELOG
- [x] Increased delay for IAP helper workloads to increase reliability of the deployment
- [x] Tested manually on GKE 1.22.

### CODE REVIEW

**Review by chensun — COMMENTED** [review]
/lgtm

File: kubeflow/pull-upstream.sh [hunk 1]
```diff
@@ -16,9 +16,9 @@
 
 set -ex
 
-export KUBEFLOW_MANIFESTS_VERSION=v1.6.0
+export KUBEFLOW_MANIFESTS_VERSION=v1.6.1
 export KUBEFLOW_MANIFESTS_REPO=https://github.com/kubeflow/manifests.git
-export KUBEFLOW_PIPELINES_VERSION=2.0.0-alpha.4
+export KUBEFLOW_PIPELINES_VERSION=2.0.0-alpha.6
```
Comment (chensun) [inline kubeflow/pull-upstream.sh:21]: I'm curious does GCP distribution needs to align with generic distribution in terms of binary versions?
I mean `kubeflow/manifests` has released 1.6.1 with KFP 2.0.0-alpha.5. https://github.com/kubeflow/manifests/tree/v1.6.1

Comment (gkcalat) [reply kubeflow/pull-upstream.sh:21]: While we are using pre-released KFP, it shouldn't bring too many issues. Other components are in sync with the platform-agnostic Kubeflow.

File: kubeflow/asm/Makefile [hunk 2]
```diff
@@ -43,7 +43,7 @@ install-asm: download-asmcli download-asm-package
 	--project_id $(PROJECT) \
 	--cluster_name $(NAME) \
 	--cluster_location $(LOCATION) \
-	--output_dir $(UPSTREAM) \
+	--output_dir ./package \
```
Comment (zijianjoy) [inline kubeflow/asm/Makefile:46]: Should we remove `UPSTREAM` variable in line 24?

Comment (gkcalat) [reply kubeflow/asm/Makefile]: Fixed. Thank you @zijianjoy !

File: kubeflow/asm/Makefile [hunk 3]
```diff
@@ -33,9 +33,9 @@ download-asm-package:
 	rm -rf asm.tar.gz
 	curl -LJ https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/archive/refs/tags/$(ASM_PACKAGE_VERSION).tar.gz -o asm.tar.gz 
 	
-	rm -rf ./package
-	mkdir package
-	tar -xf asm.tar.gz --strip-components=1 -C package 
+	rm -rf $(UPSTREAM)
```
Comment (zijianjoy) [inline kubeflow/asm/Makefile:36]: Question: Can we use `./$(UPSTREAM)` instead of `$(UPSTREAM)`? Just want to make sure we are deleting the folder in current path.

Comment (gkcalat) [reply kubeflow/asm/Makefile:36]: Changed upstream variable to `./package`. It seems to have no effect on the results of `hydrate` and `apply` running from `kubeflow` (using config.yaml or just by running `make -C asm ...`) and directly from `asm` folders. Does it address your concern?

**Comment by zijianjoy** [comment]
Thank you Ablai! Look good to me.
